# Generated by Django 4.2.6 on 2023-10-21 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('maker', models.CharField(max_length=100, verbose_name='maker')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('region', models.CharField(max_length=100, verbose_name='region')),
                ('capacity', models.PositiveIntegerField(blank=True, verbose_name='capacity')),
                ('meter', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='meter')),
                ('base_value', models.PositiveIntegerField(verbose_name='base value')),
                ('buy_assurance', models.BooleanField(default=False, verbose_name='buy insurance')),
                ('guaranteed_gain', models.BooleanField(default=False, verbose_name='guaranteed gain')),
                ('guaranteed_gain_percent', models.PositiveIntegerField(verbose_name='guaranteed gain percent')),
                ('end_time', models.PositiveIntegerField(verbose_name='end time')),
                ('description', models.TextField(max_length=500, verbose_name='description')),
                ('status', models.CharField(choices=[('a', 'Active'), ('s', 'Soon'), ('e', 'Ended')], max_length=10, verbose_name='status')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-datetime_created',),
            },
        ),
    ]
