# Generated by Django 4.2.6 on 2023-10-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='end_time',
            field=models.CharField(max_length=200, verbose_name='end time'),
        ),
    ]
