# Generated by Django 4.2.6 on 2023-11-01 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
