# Generated by Django 4.2.6 on 2023-11-05 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_alter_case_meter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='meter',
        ),
    ]
