# Generated by Django 4.2.6 on 2023-11-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_national_code_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='national_code',
            field=models.CharField(max_length=10, verbose_name='national_code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Phone Number'),
        ),
    ]
